language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 5.5.9
      env: setup=stable

sudo: false

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-source; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-source --no-interaction --prefer-stable; fi

script:
 - mkdir -p build/logs
 - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
 - php vendor/bin/coveralls -v